### ISSUE TITLE
Sphere starting coordinates

### ISSUE THREAD

**Issue by MichaelVerdegaal** [MichaelVerdegaal/InfluenceOrbitMapper#9]
The current coordinates of a sphere are not calculated correctly. Verification can be done manually by comparing to the main Influence site. If this is invalid then the issue should lie somewhere in the position_at_adalia_day method, or the adalia day calculation itself. See image comparison below
![brave_VGbyFRc0vJ](https://user-images.githubusercontent.com/23554677/134399274-70f8a63d-1a7d-41be-9857-7196f55af053.png)
![brave_2Pj7htcwfY](https://user-images.githubusercontent.com/23554677/134399331-7f768cbb-ce5e-459a-a79a-22fac4923db3.png)

**Comment by MichaelVerdegaal** [comment]
Confirmed that the entire orbit path calculation is now correct, so the issue is at least not on that end

**Comment by jpy-luke** [comment]
The adalia days calculation does not seem to be off. Something mysterious about either the algorithm or about the xyz axes compared to the plot library xyz axes. z-axis becomes flipped.

1) When I set position_at_adalia_day function to return np.array([x, y, -z]), it draws correct positions and orbits looks same as in the game. However, the star is in the wrong focal point. Orbit epoc is 180 degrees off.
2) When I set M = m + 180 + (n * adalia_day), but wihtout the -z from point 1, the system seems like it should.

I can't yet explain why this is so. I'll make a PR if I do figure it out.
It's Montressor from Discord btw.

**Comment by jpy-luke** [comment]
Oh never mind the ramblings above. They manage to circumvent the problem. I think I found it.

influce-utils file lists 
const START_TIMESTAMP = 1609459200; // Zero date timestamp for orbits

However:
$ date --date='@1609459200'
Fri Jan  1 02:00:00 EET 2021

When I fix orbits.py to
START_TIMESTAMP = '2021-01-01T00:00:00+00:00'
The same fix in the positions is achieved.

**Comment by MichaelVerdegaal** [comment]
Fixed as of https://github.com/MichaelVerdegaal/InfluenceOrbitMapper/pull/11
